const ChatResponses = [
  "The cat (Felis catus), also called domestic cat and house cat, is a small carnivorous mammal. It is an obligate carnivore, requiring a predominantly meat-based diet. Its retractable claws are adapted to killing small prey species such as mice and rats. It has a strong, flexible body, quick reflexes, and sharp teeth, and its night vision and sense of smell are well developed. It is a social species, but a solitary hunter and a crepuscular predator.",
  "Cat communication includes meowing, purring, trilling, hissing, growling, grunting, and body language. It can hear sounds too faint or too high in frequency for human ears, such as those made by small mammals.",
  "The domestic cat is the only domesticated species of the family Felidae. Advances in archaeology and genetics have shown that the domestication of the cat started in the Near East around 7500 BCE.",
  "Out of the estimated 600 million domestic cats worldwide, 400 million reside in Asia, including 58 million in China. About 73.8 million cats are estimated to live in the United States, and about 10.9 million cats the United Kingdom.",
  "The origin of the English word cat, Old English catt, is thought to be the Late Latin word cattus, which was first used at the beginning of the 6th century. The Late Latin word may be derived from an unidentified African language. The Nubian word kaddîska 'wildcat' and Nobiin kadīs are possible sources or cognates.",
  "The domestic cat is a member of the Felidae, a family that has a common ancestor from about 10 to 15 million years ago. The evolutionary radiation of the Felidae began in Asia during the Miocene around 8.38 to 14.45 million years ago.",
  "Mafdet was the first known cat-headed deity in ancient Egypt. During the First Dynasty, she was regarded as protector of the pharaoh's chambers against snakes, scorpions and evil. She was often also depicted with a head of a leopard (Panthera pardus) or a cheetah (Acinonyx jubatus). She was particularly prominent during the reign of Den.",
  "A tomb at the necropolis Umm El Qa'ab contained 17 cat skeletons dating to the early 20th century BC. Next to the skeletons stood small pots that are thought to have contained milk for the cats. Several tomb murals in the Theban Necropolis show cats in domestic scenes. These tombs belonged to nobles and high-ranking officials of the 18th Dynasty and were built in the 15th and 14th centuries BC. The murals show a cat sitting under a chair during a buffet, eating meat or fish; some show it in the company of a goose or a monkey. A cat in hunting and fowling scenes is another recurring motif in murals of Theban tombs.",
  "The lineage of today's cats stems from about 4500 BC and came from Europe and Southeast Asia according to a recent study. Modern cats stem from two major lines of lineage.",
  "Cats that were favored pets during the Chinese Song dynasty were long-haired cats for catching rats, and cats with yellow-and-white fur called 'lion-cats', who were valued simply as cute pets. Cats could be pampered with items bought from the market such as \"cat-nests\", and were often fed fish that were advertised in the market specifically for cats.",
  "Although Russia is geographically located in Europe, attitudes toward cats there have always been radically different from those in Central and Western Europe. Orthodox Christianity not only did not persecute these animals, but rather had an entirely positive attitude toward them. Unlike in Western countries, cats have been considered good luck in Russia for centuries. Owning a cat, and especially letting one into a new house before the humans move in, is said to bring good fortune. Cats in Orthodox Christianity are the only animals that are allowed to enter the temples. Also, cats were an integral attribute of Russian Orthodox monasteries. According to Russian law, a huge fine was imposed for killing a cat, the same as for a horse or ox.",
  "The Greeks later syncretized their own goddess Artemis with the Egyptian goddess Bastet, adopting Bastet's associations with cats and ascribing them to Artemis. In Ovid's Metamorphoses, when the gods flee to Egypt and take animal forms, the goddess Diana (the Roman equivalent of Artemis) turns into a cat. Cats eventually displaced ferrets as the pest control of choice because they were more pleasant to have around the house and were more enthusiastic hunters of mice.",
  "During domestication, cats have undergone only minor changes in anatomy and behavior, and they are still capable of surviving in the wild. Several natural behaviors and characteristics of wildcats may have pre-adapted them for domestication as pets. These traits include their small size, social nature, obvious body language, love of play, and high intelligence. Their rigorous grooming habits and instinct to bury their bodily waste make them generally much less messy than other domesticated animals. Captive Leopardus cats may also display affectionate behavior toward humans but are not domesticated.",
  "Domestic cats observed in rescue facilities have 276 morphologically distinct facial expressions based on 26 facial movements; each facial expression corresponds to different social functions that are probably influenced by domestication.",
  "The domestic cat is a cosmopolitan species and occurs across much of the world. It is adaptable and now present on all continents except Antarctica, and on 118 of the 131 main groups of islands, even on the remote Kerguelen Islands. Due to its ability to thrive in almost any terrestrial habitat, it is among the world's most invasive species.[203] It lives on small islands with no human inhabitants. Feral cats can live in forests, grasslands, tundra, coastal areas, agricultural land, scrublands, urban areas, and wetlands.",
  "A few attempts to build a cat census have been made over the years, both through associations or national and international organizations (such as that of the Canadian Federation of Humane Societies) and over the Internet. General estimates for the global population of domestic cats range widely from anywhere between 200 million to 600 million.",
]

export default ChatResponses;